# Generated by Django 3.2.3 on 2021-06-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_homecarousel_options'),
        ('users', '0002_emailsubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist_product',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
