# Generated by Django 3.2.3 on 2021-06-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image2'),
        ('users', '0003_user_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_product',
            field=models.ManyToManyField(blank=True, related_name='like_products', to='products.Product', verbose_name='Like Products'),
        ),
    ]
