# Generated by Django 3.2.3 on 2021-06-30 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_label'),
        ('users', '0005_auto_20210630_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwishlist',
            name='product',
        ),
        migrations.CreateModel(
            name='UserWihslistProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userwishlist')),
            ],
        ),
    ]
