# Generated by Django 3.2.3 on 2021-06-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_label'),
        ('users', '0006_auto_20210630_1152'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwihslistproduct',
            unique_together={('wishlist', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='userwishlist',
            unique_together={('user', 'name')},
        ),
        migrations.AlterModelTable(
            name='userwihslistproduct',
            table='wishlist_product',
        ),
        migrations.AlterModelTable(
            name='userwishlist',
            table='wishlist',
        ),
    ]
