# Generated by Django 3.2.3 on 2021-05-19 07:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={},
        ),
        migrations.RemoveField(
            model_name='color',
            name='order',
        ),
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
