# Generated by Django 3.2.3 on 2021-05-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
