# Generated by Django 3.2.3 on 2021-05-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_remove_myuser_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_active',
            new_name='is_staff',
        ),
    ]
