# Generated by Django 3.2.3 on 2021-05-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_rename_is_active_myuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
    ]
