# Generated by Django 3.2.3 on 2021-06-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='redirect_url',
            field=models.URLField(max_length=2000),
        ),
    ]
