# Generated by Django 3.2.3 on 2021-06-03 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'merchant',
                'ordering': ['display_order'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.merchant'),
        ),
    ]
