# Generated by Django 3.2.3 on 2021-06-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_homecarousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecarousel',
            options={'ordering': ['display_order'], 'verbose_name': 'Home Carousels', 'verbose_name_plural': 'Home Carousels'},
        ),
    ]
